"""Social upload API endpoints."""

from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException

from app.core.config import settings
from app.services.auth_service import get_current_active_user
from app.services.social_upload import SocialUploader

router = APIRouter(prefix="/upload", tags=["upload"])


@router.post("/{platform}")
async def upload_to_platform(
    platform: str,
    story_id: str,
    _=Depends(get_current_active_user),
) -> dict:
    uploader = SocialUploader()
    video_path = Path(settings.STORAGE_LOCAL_PATH) / "videos" / f"{story_id}.mp4"
    if not video_path.exists():
        raise HTTPException(status_code=404, detail="Video not found")

    return await uploader.upload(
        platform=platform,
        video_path=video_path,
        title=f"Story Reel {story_id}",
        description="Generated by Story Reels AI",
    )
